import '@/styles/globals.css'

import { Poppins, Bricolage_Grotesque } from 'next/font/google'
import { type Metadata } from 'next'

import { TRPCReactProvider } from '@/trpc/react'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
    title: 'Create T3 App',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

const poppins = Poppins({
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
    variable: '--font-sans',
})

const bricolage_grotesque = Bricolage_Grotesque({
    subsets: ['latin'],
    variable: '--font-serif',
})

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html
            lang="en"
            className={cn(
                'latte',
                poppins.variable,
                bricolage_grotesque.variable
            )}
        >
            <body>
                <TRPCReactProvider>{children}</TRPCReactProvider>
            </body>
        </html>
    )
}
