import '@/styles/globals.css'

import { Poppins, Bricolage_Grotesque } from 'next/font/google'
import { type Metadata } from 'next'

import { TRPCReactProvider } from '@/trpc/react'

import { Toaster } from '@/components/ui/toaster'

export const metadata: Metadata = {
    title: 'Create T3 App',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

const poppins = Poppins({
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
    variable: '--font-sans',
})

const bricolage_grotesque = Bricolage_Grotesque({
    subsets: ['latin'],
    variable: '--font-serif',
})

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html
            lang="en"
            className={`${poppins.variable} ${bricolage_grotesque.variable} latte`}
        >
            <body>
                <TRPCReactProvider>
                    {children}
                    <Toaster />
                </TRPCReactProvider>
            </body>
        </html>
    )
}
